config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :hospitals do
    resources :doctors do
      resources :records
    end
  end
  root 'hospitals#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :hospital
  has_many :records
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :doctors
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :doctor

  validates :time_at, uniqueness: {scope: :doctor}, presence: true
  validates :name, presence: true
  validates :phone, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_hospital
  # before_action :set_doctor, except: [:create]

  def create
    @doctor = @hospital.doctors.create(doctor_params)
    redirect_to @hospital
  end

  def show
    @doctor = @hospital.doctors.find(params[:id])
  end

  private

  def set_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end

  def set_doctor
    @doctor = @hospital.doctors.find(params[:id])
  end

  def doctor_params
    params[:doctor].permit(:name, :specialization)
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def index
    @hospitals = Hospital.all
  end

  def create
    @hospital = Hospital.create(hospital_params)
    redirect_to root_path
  end

  def new
    @hospital = Hospital.new
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  private

  def hospital_params
    params.require(:hospital).permit(:name, :city, :address)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_hospital
  before_action :set_doctor

  def new
    @record = Record.new
  end

  def create
    @record = @doctor.records.new(record_params)
    if @record.save
      redirect_to hospital_doctor_path(@hospital.id, @doctor.id)
    else
      render :new
    end
  end


  private

  def set_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end

  def set_doctor
    @doctor = @hospital.doctors.find(params[:doctor_id])
  end

  def record_params
    params[:record].permit(:name, :phone, :time_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/_doctor.html.slim
tbody
  tr
    td = link_to doctor.name, hospital_doctor_path(doctor.hospital_id, doctor.id)
    td = doctor.specialization

app/views/doctors/show.html.slim
div.jumbotron.text-center
  h1 = @doctor.name
  p = @doctor.specialization
  = link_to 'New record', new_hospital_doctor_record_path(@doctor.hospital_id, @doctor.id)
- if @doctor.records.empty?
  span.text-warning There are no records!
- else
  table.table.table-hover.table-bordered
    thead
      tr
        th Name
        th Phone
        th Time
    = render @doctor.records.sort_by {|e| e[:time_at]}

app/views/hospitals/index.html.slim
.row-fluid
  .span10.offset1
    div.page-header.text-center
      h1 Queue
      p Welcome to Online Queue application! This application allows you register at real queue to doctors.

- @hospitals.each do |h|
  .col-sm-3
    .thumbnail
      .caption
        h3 = h.name
        p = h.city
        p = h.address
        p = link_to 'Open', h

app/views/hospitals/show.html.slim
.div.jumbotron.text-center
  h1 = @hospital.name
  p = @hospital.city
  p = @hospital.address
- if @hospital.doctors.empty?
  span.text-warning There are no doctors!
- else
  table.table.table-hover.table-bordered
    thead
      tr
        th Name
        th Specialization
      = render @hospital.doctors.sort_by {|e| e[:specialization]}

app/views/layouts/_menu.html.slim
navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav
      li
        = link_to '<i class="glyphicon glyphicon-home"></i> Home'.html_safe, root_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title QueueOnline
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      header
        = render 'layouts/menu'
      = yield

app/views/records/_record.html.slim
- if record.time_at > Time.now
  tbody
    tr
      td = record.name
      td = record.phone
      td.text-info = record.time_at

app/views/records/new.html.slim
= bootstrap_form_for([@hospital, @doctor, @doctor.records.build]) do |f|
  = f.text_field :name, placeholder: "Name"
  = @record.errors.messages[:name].first if @record.errors.any? && @record.errors.messages[:name]
  = f.text_field :phone, placeholder: "Phone"
  = @record.errors.messages[:phone].first if @record.errors.any? && @record.errors.messages[:phone]
  = f.datetime_select :time_at, :minute_step => 30, :start_year => 2016, :start_hour => 9, :end_hour => 16
  = @record.errors.messages[:time_at].first if @record.errors.any? && @record.errors.messages[:time_at]
  = f.submit "Create", class: 'btn-primary'